dist: xenial

language: php

php: "7.4"

before_install:
  - nvm install
  - nvm use

install:
  - npm install

jobs:

  include:

    - php: "5.6"
      script:
        - npm run lint
        - npm run build

    - php: "7.4"
      script:
        - npm run lint
        - npm run build

notifications:
  email: false

cache:
  npm: true
  directories:
    - "$HOME/.composer/cache"
