dist: xenial

language: php

php: "7.4"

before_install:
  - nvm install
  - nvm use

install:
  - npm install

jobs:

  include:

    - stage: test
      name: Default Test and Build
      script:
        - npm run lint
        - npm run test
        - npm run build
        - npm run package

notifications:
  email: false

cache:
  npm: true
  directories:
    - "$HOME/.composer/cache"
