blank_issues_enabled: false

contact_links:

  - name: WordPress Plugin Support
    url: https://wordpress.org/support/plugin/cloudinary-image-management-and-manipulation-in-the-cloud-cdn/
    about: Please ask and answer questions here.
